#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

client_message "set postgres-connection called";

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=$(echo "$ip" | sed "s/:/[/g")
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

echo $list > $OPENSHIFT_ALINOUS_DIR/env/OPENSHIFT_JBOSSAS_CLUSTER_REMOTING



